"""empty message

Revision ID: 3dcbf5f7b460
Revises: ae9ce3d59765
Create Date: 2024-09-09 13:19:43.842045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcbf5f7b460'
down_revision: Union[str, None] = 'ae9ce3d59765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'city')
    op.drop_column('model', 'age')
    # ### end Alembic commands ###
