"""empty message

Revision ID: 8202c71bca8e
Revises: 3dcbf5f7b460
Create Date: 2024-09-09 13:57:49.878951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8202c71bca8e'
down_revision: Union[str, None] = '3dcbf5f7b460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('chest', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'chest')
    op.drop_column('model', 'height')
    op.drop_column('model', 'weight')
    # ### end Alembic commands ###
