"""empty message

Revision ID: ea22745513fe
Revises: 
Create Date: 2024-09-30 17:49:25.798757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea22745513fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('chest', sa.Integer(), nullable=True),
    sa.Column('img', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cloth', sa.String(), nullable=True),
    sa.Column('shoes', sa.Integer(), nullable=True),
    sa.Column('hair', sa.String(), nullable=True),
    sa.Column('appereance', sa.String(), nullable=True),
    sa.Column('day_1_hour', sa.Integer(), nullable=True),
    sa.Column('day_2_hour', sa.Integer(), nullable=True),
    sa.Column('night_1_hour', sa.Integer(), nullable=True),
    sa.Column('night_all', sa.Integer(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chatID', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('model')
    # ### end Alembic commands ###
